# Generated by Django 3.1.1 on 2021-04-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('DELIVERED', 'Delivered')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(),
        ),
    ]
