# Generated by Django 3.1.1 on 2021-04-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210406_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='movie',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default=('AUDIO',), max_length=10),
        ),
    ]
