# Generated by Django 3.1.1 on 2021-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
