# Generated by Django 3.1.1 on 2021-04-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_product_productimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='movie',
        ),
    ]
